tasks.release-plz = "./scripts/release-plz.sh"

[tools]
hk = 'latest'
pkl = 'latest'
jactionlint = "2.1.0"
git-cliff = 'latest'
gh = 'latest'
communique = { version = 'latest', minimum_release_age = '0s' }
